fail_fast: false
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-tabs
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args:
          - -i
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
          - --maxkb=2048
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^.gitignore$
        args:
          - --unique
