new_local_repository = use_repo_rule(
    "@bazel_tools//tools/build_defs/repo:local.bzl",
    "new_local_repository",
)

# C++ bazel rules
bazel_dep(name = "rules_cc", version = "0.2.16")

# CUDA rules
bazel_dep(name = "rules_cuda", version = "0.2.5")

cuda = use_extension("@rules_cuda//cuda:extensions.bzl", "toolchain")

# Might be required for sm_70 if your system CUDA is newer than 12.9
# cuda.local_toolchain(
#     name = "local_cuda",
#     toolkit_path = "/opt/cuda-12.9",
# )

# use_repo(cuda, "local_cuda")

# register_toolchains(
#     "@local_cuda//toolchain:nvcc-local-toolchain",
#     "@local_cuda//toolchain/clang:clang-local-toolchain",
#     "@local_cuda//toolchain/disabled:disabled-local-toolchain",
# )

# Abseil
bazel_dep(name = "abseil-cpp", version = "20260107.0")

# spdlog
bazel_dep(name = "spdlog", version = "1.17.0")

# GoogleTest
bazel_dep(name = "googletest", version = "1.17.0")

# Benchmark
bazel_dep(name = "google_benchmark", version = "1.9.5")

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/mikael-s-persson/bazel-compile-commands-extractor.git",
    commit = "02d15621b528efd877f5d5657c4b738523a0eb17",
    # remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    # commit = "4f28899228fb3ad0126897876f147ca15026151e",
)
