cc_test(
    name = "harm_data_test",
    size = "small",
    srcs = ["harm_data_test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//cuda_grmonty:harm_data",
    ],
)
